# CMake generated Testfile for 
# Source directory: /home/marcel.mukundi/rmacxx
# Build directory: /home/marcel.mukundi/rmacxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bench_ncontig_data.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_ncontig_data.cpp")
set_tests_properties(bench_ncontig_data.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_prmabwtest.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_prmabwtest.cpp")
set_tests_properties(bench_prmabwtest.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_acc.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_acc.cpp")
set_tests_properties(bench_simple_acc.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_cas.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_cas.cpp")
set_tests_properties(bench_simple_cas.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_expr.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_expr.cpp")
set_tests_properties(bench_simple_expr.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_expr2.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_expr2.cpp")
set_tests_properties(bench_simple_expr2.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_fop.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_fop.cpp")
set_tests_properties(bench_simple_fop.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_gacc.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_gacc.cpp")
set_tests_properties(bench_simple_gacc.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_get.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_get.cpp")
set_tests_properties(bench_simple_get.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put.cpp")
set_tests_properties(bench_simple_put.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put_bulk.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put_bulk.cpp")
set_tests_properties(bench_simple_put_bulk.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put_concurrent.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put_concurrent.cpp")
set_tests_properties(bench_simple_put_concurrent.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put_gv.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put_gv.cpp")
set_tests_properties(bench_simple_put_gv.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put_gv_strided.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put_gv_strided.cpp")
set_tests_properties(bench_simple_put_gv_strided.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put_strided.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put_strided.cpp")
set_tests_properties(bench_simple_put_strided.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
add_test(bench_simple_put_strided_2D.cpp "mpiexec" "--np" "20" "/home/marcel.mukundi/rmacxx/bench_simple_put_strided_2D.cpp")
set_tests_properties(bench_simple_put_strided_2D.cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/marcel.mukundi/rmacxx/CMakeLists.txt;36;add_test;/home/marcel.mukundi/rmacxx/CMakeLists.txt;0;")
