# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /weka/apps/cmake/3.17.0/intel/20.0/bin/cmake

# The command to remove a file.
RM = /weka/apps/cmake/3.17.0/intel/20.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcel.mukundi/rmacxx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcel.mukundi/rmacxx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/weka/apps/cmake/3.17.0/intel/20.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/weka/apps/cmake/3.17.0/intel/20.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcel.mukundi/rmacxx/CMakeFiles /home/marcel.mukundi/rmacxx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcel.mukundi/rmacxx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named bench_simple_cas.cpp

# Build rule for target.
bench_simple_cas.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_cas.cpp
.PHONY : bench_simple_cas.cpp

# fast build rule for target.
bench_simple_cas.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_cas.cpp.dir/build.make CMakeFiles/bench_simple_cas.cpp.dir/build
.PHONY : bench_simple_cas.cpp/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named bench_simple_expr2.cpp

# Build rule for target.
bench_simple_expr2.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_expr2.cpp
.PHONY : bench_simple_expr2.cpp

# fast build rule for target.
bench_simple_expr2.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_expr2.cpp.dir/build.make CMakeFiles/bench_simple_expr2.cpp.dir/build
.PHONY : bench_simple_expr2.cpp/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named bench_simple_put.cpp

# Build rule for target.
bench_simple_put.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put.cpp
.PHONY : bench_simple_put.cpp

# fast build rule for target.
bench_simple_put.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put.cpp.dir/build.make CMakeFiles/bench_simple_put.cpp.dir/build
.PHONY : bench_simple_put.cpp/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named bench_simple_acc.cpp

# Build rule for target.
bench_simple_acc.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_acc.cpp
.PHONY : bench_simple_acc.cpp

# fast build rule for target.
bench_simple_acc.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_acc.cpp.dir/build.make CMakeFiles/bench_simple_acc.cpp.dir/build
.PHONY : bench_simple_acc.cpp/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named bench_simple_put_concurrent.cpp

# Build rule for target.
bench_simple_put_concurrent.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put_concurrent.cpp
.PHONY : bench_simple_put_concurrent.cpp

# fast build rule for target.
bench_simple_put_concurrent.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put_concurrent.cpp.dir/build.make CMakeFiles/bench_simple_put_concurrent.cpp.dir/build
.PHONY : bench_simple_put_concurrent.cpp/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named bench_simple_put_strided_2D.cpp

# Build rule for target.
bench_simple_put_strided_2D.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put_strided_2D.cpp
.PHONY : bench_simple_put_strided_2D.cpp

# fast build rule for target.
bench_simple_put_strided_2D.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided_2D.cpp.dir/build.make CMakeFiles/bench_simple_put_strided_2D.cpp.dir/build
.PHONY : bench_simple_put_strided_2D.cpp/fast

#=============================================================================
# Target rules for targets named bench_ncontig_data.cpp

# Build rule for target.
bench_ncontig_data.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_ncontig_data.cpp
.PHONY : bench_ncontig_data.cpp

# fast build rule for target.
bench_ncontig_data.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_ncontig_data.cpp.dir/build.make CMakeFiles/bench_ncontig_data.cpp.dir/build
.PHONY : bench_ncontig_data.cpp/fast

#=============================================================================
# Target rules for targets named bench_simple_fop.cpp

# Build rule for target.
bench_simple_fop.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_fop.cpp
.PHONY : bench_simple_fop.cpp

# fast build rule for target.
bench_simple_fop.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_fop.cpp.dir/build.make CMakeFiles/bench_simple_fop.cpp.dir/build
.PHONY : bench_simple_fop.cpp/fast

#=============================================================================
# Target rules for targets named bench_prmabwtest.cpp

# Build rule for target.
bench_prmabwtest.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_prmabwtest.cpp
.PHONY : bench_prmabwtest.cpp

# fast build rule for target.
bench_prmabwtest.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_prmabwtest.cpp.dir/build.make CMakeFiles/bench_prmabwtest.cpp.dir/build
.PHONY : bench_prmabwtest.cpp/fast

#=============================================================================
# Target rules for targets named bench_simple_get.cpp

# Build rule for target.
bench_simple_get.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_get.cpp
.PHONY : bench_simple_get.cpp

# fast build rule for target.
bench_simple_get.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_get.cpp.dir/build.make CMakeFiles/bench_simple_get.cpp.dir/build
.PHONY : bench_simple_get.cpp/fast

#=============================================================================
# Target rules for targets named bench_simple_put_strided.cpp

# Build rule for target.
bench_simple_put_strided.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put_strided.cpp
.PHONY : bench_simple_put_strided.cpp

# fast build rule for target.
bench_simple_put_strided.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_strided.cpp.dir/build
.PHONY : bench_simple_put_strided.cpp/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named bench_simple_expr.cpp

# Build rule for target.
bench_simple_expr.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_expr.cpp
.PHONY : bench_simple_expr.cpp

# fast build rule for target.
bench_simple_expr.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_expr.cpp.dir/build.make CMakeFiles/bench_simple_expr.cpp.dir/build
.PHONY : bench_simple_expr.cpp/fast

#=============================================================================
# Target rules for targets named bench_simple_gacc.cpp

# Build rule for target.
bench_simple_gacc.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_gacc.cpp
.PHONY : bench_simple_gacc.cpp

# fast build rule for target.
bench_simple_gacc.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_gacc.cpp.dir/build.make CMakeFiles/bench_simple_gacc.cpp.dir/build
.PHONY : bench_simple_gacc.cpp/fast

#=============================================================================
# Target rules for targets named bench_simple_put_bulk.cpp

# Build rule for target.
bench_simple_put_bulk.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put_bulk.cpp
.PHONY : bench_simple_put_bulk.cpp

# fast build rule for target.
bench_simple_put_bulk.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put_bulk.cpp.dir/build.make CMakeFiles/bench_simple_put_bulk.cpp.dir/build
.PHONY : bench_simple_put_bulk.cpp/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named bench_simple_put_gv.cpp

# Build rule for target.
bench_simple_put_gv.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put_gv.cpp
.PHONY : bench_simple_put_gv.cpp

# fast build rule for target.
bench_simple_put_gv.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv.cpp.dir/build.make CMakeFiles/bench_simple_put_gv.cpp.dir/build
.PHONY : bench_simple_put_gv.cpp/fast

#=============================================================================
# Target rules for targets named bench_simple_put_gv_strided.cpp

# Build rule for target.
bench_simple_put_gv_strided.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_simple_put_gv_strided.cpp
.PHONY : bench_simple_put_gv_strided.cpp

# fast build rule for target.
bench_simple_put_gv_strided.cpp/fast:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_gv_strided.cpp.dir/build
.PHONY : bench_simple_put_gv_strided.cpp/fast

benchmarks/ncontig_data.o: benchmarks/ncontig_data.cpp.o

.PHONY : benchmarks/ncontig_data.o

# target to build an object file
benchmarks/ncontig_data.cpp.o:
	$(MAKE) -f CMakeFiles/bench_ncontig_data.cpp.dir/build.make CMakeFiles/bench_ncontig_data.cpp.dir/benchmarks/ncontig_data.cpp.o
.PHONY : benchmarks/ncontig_data.cpp.o

benchmarks/ncontig_data.i: benchmarks/ncontig_data.cpp.i

.PHONY : benchmarks/ncontig_data.i

# target to preprocess a source file
benchmarks/ncontig_data.cpp.i:
	$(MAKE) -f CMakeFiles/bench_ncontig_data.cpp.dir/build.make CMakeFiles/bench_ncontig_data.cpp.dir/benchmarks/ncontig_data.cpp.i
.PHONY : benchmarks/ncontig_data.cpp.i

benchmarks/ncontig_data.s: benchmarks/ncontig_data.cpp.s

.PHONY : benchmarks/ncontig_data.s

# target to generate assembly for a file
benchmarks/ncontig_data.cpp.s:
	$(MAKE) -f CMakeFiles/bench_ncontig_data.cpp.dir/build.make CMakeFiles/bench_ncontig_data.cpp.dir/benchmarks/ncontig_data.cpp.s
.PHONY : benchmarks/ncontig_data.cpp.s

benchmarks/prmabwtest.o: benchmarks/prmabwtest.cpp.o

.PHONY : benchmarks/prmabwtest.o

# target to build an object file
benchmarks/prmabwtest.cpp.o:
	$(MAKE) -f CMakeFiles/bench_prmabwtest.cpp.dir/build.make CMakeFiles/bench_prmabwtest.cpp.dir/benchmarks/prmabwtest.cpp.o
.PHONY : benchmarks/prmabwtest.cpp.o

benchmarks/prmabwtest.i: benchmarks/prmabwtest.cpp.i

.PHONY : benchmarks/prmabwtest.i

# target to preprocess a source file
benchmarks/prmabwtest.cpp.i:
	$(MAKE) -f CMakeFiles/bench_prmabwtest.cpp.dir/build.make CMakeFiles/bench_prmabwtest.cpp.dir/benchmarks/prmabwtest.cpp.i
.PHONY : benchmarks/prmabwtest.cpp.i

benchmarks/prmabwtest.s: benchmarks/prmabwtest.cpp.s

.PHONY : benchmarks/prmabwtest.s

# target to generate assembly for a file
benchmarks/prmabwtest.cpp.s:
	$(MAKE) -f CMakeFiles/bench_prmabwtest.cpp.dir/build.make CMakeFiles/bench_prmabwtest.cpp.dir/benchmarks/prmabwtest.cpp.s
.PHONY : benchmarks/prmabwtest.cpp.s

benchmarks/simple_acc.o: benchmarks/simple_acc.cpp.o

.PHONY : benchmarks/simple_acc.o

# target to build an object file
benchmarks/simple_acc.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_acc.cpp.dir/build.make CMakeFiles/bench_simple_acc.cpp.dir/benchmarks/simple_acc.cpp.o
.PHONY : benchmarks/simple_acc.cpp.o

benchmarks/simple_acc.i: benchmarks/simple_acc.cpp.i

.PHONY : benchmarks/simple_acc.i

# target to preprocess a source file
benchmarks/simple_acc.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_acc.cpp.dir/build.make CMakeFiles/bench_simple_acc.cpp.dir/benchmarks/simple_acc.cpp.i
.PHONY : benchmarks/simple_acc.cpp.i

benchmarks/simple_acc.s: benchmarks/simple_acc.cpp.s

.PHONY : benchmarks/simple_acc.s

# target to generate assembly for a file
benchmarks/simple_acc.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_acc.cpp.dir/build.make CMakeFiles/bench_simple_acc.cpp.dir/benchmarks/simple_acc.cpp.s
.PHONY : benchmarks/simple_acc.cpp.s

benchmarks/simple_cas.o: benchmarks/simple_cas.cpp.o

.PHONY : benchmarks/simple_cas.o

# target to build an object file
benchmarks/simple_cas.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_cas.cpp.dir/build.make CMakeFiles/bench_simple_cas.cpp.dir/benchmarks/simple_cas.cpp.o
.PHONY : benchmarks/simple_cas.cpp.o

benchmarks/simple_cas.i: benchmarks/simple_cas.cpp.i

.PHONY : benchmarks/simple_cas.i

# target to preprocess a source file
benchmarks/simple_cas.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_cas.cpp.dir/build.make CMakeFiles/bench_simple_cas.cpp.dir/benchmarks/simple_cas.cpp.i
.PHONY : benchmarks/simple_cas.cpp.i

benchmarks/simple_cas.s: benchmarks/simple_cas.cpp.s

.PHONY : benchmarks/simple_cas.s

# target to generate assembly for a file
benchmarks/simple_cas.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_cas.cpp.dir/build.make CMakeFiles/bench_simple_cas.cpp.dir/benchmarks/simple_cas.cpp.s
.PHONY : benchmarks/simple_cas.cpp.s

benchmarks/simple_expr.o: benchmarks/simple_expr.cpp.o

.PHONY : benchmarks/simple_expr.o

# target to build an object file
benchmarks/simple_expr.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_expr.cpp.dir/build.make CMakeFiles/bench_simple_expr.cpp.dir/benchmarks/simple_expr.cpp.o
.PHONY : benchmarks/simple_expr.cpp.o

benchmarks/simple_expr.i: benchmarks/simple_expr.cpp.i

.PHONY : benchmarks/simple_expr.i

# target to preprocess a source file
benchmarks/simple_expr.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_expr.cpp.dir/build.make CMakeFiles/bench_simple_expr.cpp.dir/benchmarks/simple_expr.cpp.i
.PHONY : benchmarks/simple_expr.cpp.i

benchmarks/simple_expr.s: benchmarks/simple_expr.cpp.s

.PHONY : benchmarks/simple_expr.s

# target to generate assembly for a file
benchmarks/simple_expr.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_expr.cpp.dir/build.make CMakeFiles/bench_simple_expr.cpp.dir/benchmarks/simple_expr.cpp.s
.PHONY : benchmarks/simple_expr.cpp.s

benchmarks/simple_expr2.o: benchmarks/simple_expr2.cpp.o

.PHONY : benchmarks/simple_expr2.o

# target to build an object file
benchmarks/simple_expr2.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_expr2.cpp.dir/build.make CMakeFiles/bench_simple_expr2.cpp.dir/benchmarks/simple_expr2.cpp.o
.PHONY : benchmarks/simple_expr2.cpp.o

benchmarks/simple_expr2.i: benchmarks/simple_expr2.cpp.i

.PHONY : benchmarks/simple_expr2.i

# target to preprocess a source file
benchmarks/simple_expr2.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_expr2.cpp.dir/build.make CMakeFiles/bench_simple_expr2.cpp.dir/benchmarks/simple_expr2.cpp.i
.PHONY : benchmarks/simple_expr2.cpp.i

benchmarks/simple_expr2.s: benchmarks/simple_expr2.cpp.s

.PHONY : benchmarks/simple_expr2.s

# target to generate assembly for a file
benchmarks/simple_expr2.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_expr2.cpp.dir/build.make CMakeFiles/bench_simple_expr2.cpp.dir/benchmarks/simple_expr2.cpp.s
.PHONY : benchmarks/simple_expr2.cpp.s

benchmarks/simple_fop.o: benchmarks/simple_fop.cpp.o

.PHONY : benchmarks/simple_fop.o

# target to build an object file
benchmarks/simple_fop.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_fop.cpp.dir/build.make CMakeFiles/bench_simple_fop.cpp.dir/benchmarks/simple_fop.cpp.o
.PHONY : benchmarks/simple_fop.cpp.o

benchmarks/simple_fop.i: benchmarks/simple_fop.cpp.i

.PHONY : benchmarks/simple_fop.i

# target to preprocess a source file
benchmarks/simple_fop.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_fop.cpp.dir/build.make CMakeFiles/bench_simple_fop.cpp.dir/benchmarks/simple_fop.cpp.i
.PHONY : benchmarks/simple_fop.cpp.i

benchmarks/simple_fop.s: benchmarks/simple_fop.cpp.s

.PHONY : benchmarks/simple_fop.s

# target to generate assembly for a file
benchmarks/simple_fop.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_fop.cpp.dir/build.make CMakeFiles/bench_simple_fop.cpp.dir/benchmarks/simple_fop.cpp.s
.PHONY : benchmarks/simple_fop.cpp.s

benchmarks/simple_gacc.o: benchmarks/simple_gacc.cpp.o

.PHONY : benchmarks/simple_gacc.o

# target to build an object file
benchmarks/simple_gacc.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_gacc.cpp.dir/build.make CMakeFiles/bench_simple_gacc.cpp.dir/benchmarks/simple_gacc.cpp.o
.PHONY : benchmarks/simple_gacc.cpp.o

benchmarks/simple_gacc.i: benchmarks/simple_gacc.cpp.i

.PHONY : benchmarks/simple_gacc.i

# target to preprocess a source file
benchmarks/simple_gacc.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_gacc.cpp.dir/build.make CMakeFiles/bench_simple_gacc.cpp.dir/benchmarks/simple_gacc.cpp.i
.PHONY : benchmarks/simple_gacc.cpp.i

benchmarks/simple_gacc.s: benchmarks/simple_gacc.cpp.s

.PHONY : benchmarks/simple_gacc.s

# target to generate assembly for a file
benchmarks/simple_gacc.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_gacc.cpp.dir/build.make CMakeFiles/bench_simple_gacc.cpp.dir/benchmarks/simple_gacc.cpp.s
.PHONY : benchmarks/simple_gacc.cpp.s

benchmarks/simple_get.o: benchmarks/simple_get.cpp.o

.PHONY : benchmarks/simple_get.o

# target to build an object file
benchmarks/simple_get.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_get.cpp.dir/build.make CMakeFiles/bench_simple_get.cpp.dir/benchmarks/simple_get.cpp.o
.PHONY : benchmarks/simple_get.cpp.o

benchmarks/simple_get.i: benchmarks/simple_get.cpp.i

.PHONY : benchmarks/simple_get.i

# target to preprocess a source file
benchmarks/simple_get.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_get.cpp.dir/build.make CMakeFiles/bench_simple_get.cpp.dir/benchmarks/simple_get.cpp.i
.PHONY : benchmarks/simple_get.cpp.i

benchmarks/simple_get.s: benchmarks/simple_get.cpp.s

.PHONY : benchmarks/simple_get.s

# target to generate assembly for a file
benchmarks/simple_get.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_get.cpp.dir/build.make CMakeFiles/bench_simple_get.cpp.dir/benchmarks/simple_get.cpp.s
.PHONY : benchmarks/simple_get.cpp.s

benchmarks/simple_put.o: benchmarks/simple_put.cpp.o

.PHONY : benchmarks/simple_put.o

# target to build an object file
benchmarks/simple_put.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put.cpp.dir/build.make CMakeFiles/bench_simple_put.cpp.dir/benchmarks/simple_put.cpp.o
.PHONY : benchmarks/simple_put.cpp.o

benchmarks/simple_put.i: benchmarks/simple_put.cpp.i

.PHONY : benchmarks/simple_put.i

# target to preprocess a source file
benchmarks/simple_put.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put.cpp.dir/build.make CMakeFiles/bench_simple_put.cpp.dir/benchmarks/simple_put.cpp.i
.PHONY : benchmarks/simple_put.cpp.i

benchmarks/simple_put.s: benchmarks/simple_put.cpp.s

.PHONY : benchmarks/simple_put.s

# target to generate assembly for a file
benchmarks/simple_put.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put.cpp.dir/build.make CMakeFiles/bench_simple_put.cpp.dir/benchmarks/simple_put.cpp.s
.PHONY : benchmarks/simple_put.cpp.s

benchmarks/simple_put_bulk.o: benchmarks/simple_put_bulk.cpp.o

.PHONY : benchmarks/simple_put_bulk.o

# target to build an object file
benchmarks/simple_put_bulk.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put_bulk.cpp.dir/build.make CMakeFiles/bench_simple_put_bulk.cpp.dir/benchmarks/simple_put_bulk.cpp.o
.PHONY : benchmarks/simple_put_bulk.cpp.o

benchmarks/simple_put_bulk.i: benchmarks/simple_put_bulk.cpp.i

.PHONY : benchmarks/simple_put_bulk.i

# target to preprocess a source file
benchmarks/simple_put_bulk.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put_bulk.cpp.dir/build.make CMakeFiles/bench_simple_put_bulk.cpp.dir/benchmarks/simple_put_bulk.cpp.i
.PHONY : benchmarks/simple_put_bulk.cpp.i

benchmarks/simple_put_bulk.s: benchmarks/simple_put_bulk.cpp.s

.PHONY : benchmarks/simple_put_bulk.s

# target to generate assembly for a file
benchmarks/simple_put_bulk.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put_bulk.cpp.dir/build.make CMakeFiles/bench_simple_put_bulk.cpp.dir/benchmarks/simple_put_bulk.cpp.s
.PHONY : benchmarks/simple_put_bulk.cpp.s

benchmarks/simple_put_concurrent.o: benchmarks/simple_put_concurrent.cpp.o

.PHONY : benchmarks/simple_put_concurrent.o

# target to build an object file
benchmarks/simple_put_concurrent.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put_concurrent.cpp.dir/build.make CMakeFiles/bench_simple_put_concurrent.cpp.dir/benchmarks/simple_put_concurrent.cpp.o
.PHONY : benchmarks/simple_put_concurrent.cpp.o

benchmarks/simple_put_concurrent.i: benchmarks/simple_put_concurrent.cpp.i

.PHONY : benchmarks/simple_put_concurrent.i

# target to preprocess a source file
benchmarks/simple_put_concurrent.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put_concurrent.cpp.dir/build.make CMakeFiles/bench_simple_put_concurrent.cpp.dir/benchmarks/simple_put_concurrent.cpp.i
.PHONY : benchmarks/simple_put_concurrent.cpp.i

benchmarks/simple_put_concurrent.s: benchmarks/simple_put_concurrent.cpp.s

.PHONY : benchmarks/simple_put_concurrent.s

# target to generate assembly for a file
benchmarks/simple_put_concurrent.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put_concurrent.cpp.dir/build.make CMakeFiles/bench_simple_put_concurrent.cpp.dir/benchmarks/simple_put_concurrent.cpp.s
.PHONY : benchmarks/simple_put_concurrent.cpp.s

benchmarks/simple_put_gv.o: benchmarks/simple_put_gv.cpp.o

.PHONY : benchmarks/simple_put_gv.o

# target to build an object file
benchmarks/simple_put_gv.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv.cpp.dir/build.make CMakeFiles/bench_simple_put_gv.cpp.dir/benchmarks/simple_put_gv.cpp.o
.PHONY : benchmarks/simple_put_gv.cpp.o

benchmarks/simple_put_gv.i: benchmarks/simple_put_gv.cpp.i

.PHONY : benchmarks/simple_put_gv.i

# target to preprocess a source file
benchmarks/simple_put_gv.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv.cpp.dir/build.make CMakeFiles/bench_simple_put_gv.cpp.dir/benchmarks/simple_put_gv.cpp.i
.PHONY : benchmarks/simple_put_gv.cpp.i

benchmarks/simple_put_gv.s: benchmarks/simple_put_gv.cpp.s

.PHONY : benchmarks/simple_put_gv.s

# target to generate assembly for a file
benchmarks/simple_put_gv.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv.cpp.dir/build.make CMakeFiles/bench_simple_put_gv.cpp.dir/benchmarks/simple_put_gv.cpp.s
.PHONY : benchmarks/simple_put_gv.cpp.s

benchmarks/simple_put_gv_strided.o: benchmarks/simple_put_gv_strided.cpp.o

.PHONY : benchmarks/simple_put_gv_strided.o

# target to build an object file
benchmarks/simple_put_gv_strided.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_gv_strided.cpp.dir/benchmarks/simple_put_gv_strided.cpp.o
.PHONY : benchmarks/simple_put_gv_strided.cpp.o

benchmarks/simple_put_gv_strided.i: benchmarks/simple_put_gv_strided.cpp.i

.PHONY : benchmarks/simple_put_gv_strided.i

# target to preprocess a source file
benchmarks/simple_put_gv_strided.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_gv_strided.cpp.dir/benchmarks/simple_put_gv_strided.cpp.i
.PHONY : benchmarks/simple_put_gv_strided.cpp.i

benchmarks/simple_put_gv_strided.s: benchmarks/simple_put_gv_strided.cpp.s

.PHONY : benchmarks/simple_put_gv_strided.s

# target to generate assembly for a file
benchmarks/simple_put_gv_strided.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put_gv_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_gv_strided.cpp.dir/benchmarks/simple_put_gv_strided.cpp.s
.PHONY : benchmarks/simple_put_gv_strided.cpp.s

benchmarks/simple_put_strided.o: benchmarks/simple_put_strided.cpp.o

.PHONY : benchmarks/simple_put_strided.o

# target to build an object file
benchmarks/simple_put_strided.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_strided.cpp.dir/benchmarks/simple_put_strided.cpp.o
.PHONY : benchmarks/simple_put_strided.cpp.o

benchmarks/simple_put_strided.i: benchmarks/simple_put_strided.cpp.i

.PHONY : benchmarks/simple_put_strided.i

# target to preprocess a source file
benchmarks/simple_put_strided.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_strided.cpp.dir/benchmarks/simple_put_strided.cpp.i
.PHONY : benchmarks/simple_put_strided.cpp.i

benchmarks/simple_put_strided.s: benchmarks/simple_put_strided.cpp.s

.PHONY : benchmarks/simple_put_strided.s

# target to generate assembly for a file
benchmarks/simple_put_strided.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided.cpp.dir/build.make CMakeFiles/bench_simple_put_strided.cpp.dir/benchmarks/simple_put_strided.cpp.s
.PHONY : benchmarks/simple_put_strided.cpp.s

benchmarks/simple_put_strided_2D.o: benchmarks/simple_put_strided_2D.cpp.o

.PHONY : benchmarks/simple_put_strided_2D.o

# target to build an object file
benchmarks/simple_put_strided_2D.cpp.o:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided_2D.cpp.dir/build.make CMakeFiles/bench_simple_put_strided_2D.cpp.dir/benchmarks/simple_put_strided_2D.cpp.o
.PHONY : benchmarks/simple_put_strided_2D.cpp.o

benchmarks/simple_put_strided_2D.i: benchmarks/simple_put_strided_2D.cpp.i

.PHONY : benchmarks/simple_put_strided_2D.i

# target to preprocess a source file
benchmarks/simple_put_strided_2D.cpp.i:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided_2D.cpp.dir/build.make CMakeFiles/bench_simple_put_strided_2D.cpp.dir/benchmarks/simple_put_strided_2D.cpp.i
.PHONY : benchmarks/simple_put_strided_2D.cpp.i

benchmarks/simple_put_strided_2D.s: benchmarks/simple_put_strided_2D.cpp.s

.PHONY : benchmarks/simple_put_strided_2D.s

# target to generate assembly for a file
benchmarks/simple_put_strided_2D.cpp.s:
	$(MAKE) -f CMakeFiles/bench_simple_put_strided_2D.cpp.dir/build.make CMakeFiles/bench_simple_put_strided_2D.cpp.dir/benchmarks/simple_put_strided_2D.cpp.s
.PHONY : benchmarks/simple_put_strided_2D.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... bench_ncontig_data.cpp"
	@echo "... bench_prmabwtest.cpp"
	@echo "... bench_simple_acc.cpp"
	@echo "... bench_simple_cas.cpp"
	@echo "... bench_simple_expr.cpp"
	@echo "... bench_simple_expr2.cpp"
	@echo "... bench_simple_fop.cpp"
	@echo "... bench_simple_gacc.cpp"
	@echo "... bench_simple_get.cpp"
	@echo "... bench_simple_put.cpp"
	@echo "... bench_simple_put_bulk.cpp"
	@echo "... bench_simple_put_concurrent.cpp"
	@echo "... bench_simple_put_gv.cpp"
	@echo "... bench_simple_put_gv_strided.cpp"
	@echo "... bench_simple_put_strided.cpp"
	@echo "... bench_simple_put_strided_2D.cpp"
	@echo "... benchmarks/ncontig_data.o"
	@echo "... benchmarks/ncontig_data.i"
	@echo "... benchmarks/ncontig_data.s"
	@echo "... benchmarks/prmabwtest.o"
	@echo "... benchmarks/prmabwtest.i"
	@echo "... benchmarks/prmabwtest.s"
	@echo "... benchmarks/simple_acc.o"
	@echo "... benchmarks/simple_acc.i"
	@echo "... benchmarks/simple_acc.s"
	@echo "... benchmarks/simple_cas.o"
	@echo "... benchmarks/simple_cas.i"
	@echo "... benchmarks/simple_cas.s"
	@echo "... benchmarks/simple_expr.o"
	@echo "... benchmarks/simple_expr.i"
	@echo "... benchmarks/simple_expr.s"
	@echo "... benchmarks/simple_expr2.o"
	@echo "... benchmarks/simple_expr2.i"
	@echo "... benchmarks/simple_expr2.s"
	@echo "... benchmarks/simple_fop.o"
	@echo "... benchmarks/simple_fop.i"
	@echo "... benchmarks/simple_fop.s"
	@echo "... benchmarks/simple_gacc.o"
	@echo "... benchmarks/simple_gacc.i"
	@echo "... benchmarks/simple_gacc.s"
	@echo "... benchmarks/simple_get.o"
	@echo "... benchmarks/simple_get.i"
	@echo "... benchmarks/simple_get.s"
	@echo "... benchmarks/simple_put.o"
	@echo "... benchmarks/simple_put.i"
	@echo "... benchmarks/simple_put.s"
	@echo "... benchmarks/simple_put_bulk.o"
	@echo "... benchmarks/simple_put_bulk.i"
	@echo "... benchmarks/simple_put_bulk.s"
	@echo "... benchmarks/simple_put_concurrent.o"
	@echo "... benchmarks/simple_put_concurrent.i"
	@echo "... benchmarks/simple_put_concurrent.s"
	@echo "... benchmarks/simple_put_gv.o"
	@echo "... benchmarks/simple_put_gv.i"
	@echo "... benchmarks/simple_put_gv.s"
	@echo "... benchmarks/simple_put_gv_strided.o"
	@echo "... benchmarks/simple_put_gv_strided.i"
	@echo "... benchmarks/simple_put_gv_strided.s"
	@echo "... benchmarks/simple_put_strided.o"
	@echo "... benchmarks/simple_put_strided.i"
	@echo "... benchmarks/simple_put_strided.s"
	@echo "... benchmarks/simple_put_strided_2D.o"
	@echo "... benchmarks/simple_put_strided_2D.i"
	@echo "... benchmarks/simple_put_strided_2D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

