name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: ["mpich", "openmpi"]
    name: ${{ matrix.mpi }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        env:
          CC: gcc-11
          CXX: g++-11
      - run: make -C tests check -k -B
